-- task4_queries.sql

-- Total quantity of each product sold
SELECT product_id, SUM(quantity) AS total_quantity_sold
FROM Orders
GROUP BY product_id;

-- Average price of products by category
SELECT category, AVG(price) AS average_price
FROM Products
GROUP BY category;

-- Number of users signed up each year
SELECT strftime('%Y', created_at) AS signup_year, COUNT(*) AS user_count
FROM Users
GROUP BY signup_year;

-- Total revenue generated by each product (price * quantity)
SELECT P.product_id, P.name, SUM(P.price * O.quantity) AS total_revenue
FROM Products P
JOIN Orders O ON P.product_id = O.product_id
GROUP BY P.product_id, P.name;

-- Find categories where average product price is above 1000
SELECT category, AVG(price) AS avg_price
FROM Products
GROUP BY category
HAVING AVG(price) > 1000;

-- Count of distinct users who ordered each product
SELECT product_id, COUNT(DISTINCT user_id) AS unique_buyers
FROM Orders
GROUP BY product_id;

-- Highest quantity ordered per user
SELECT user_id, MAX(quantity) AS max_quantity_ordered
FROM Orders
GROUP BY user_id;